# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /u/acraig/libraryTest/linalgcpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /u/acraig/libraryTest/linalgcpp/tests

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /u/acraig/libraryTest/linalgcpp/tests/CMakeFiles /u/acraig/libraryTest/linalgcpp/tests/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /u/acraig/libraryTest/linalgcpp/tests/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named linalgcpp

# Build rule for target.
linalgcpp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 linalgcpp
.PHONY : linalgcpp

# fast build rule for target.
linalgcpp/fast:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/build
.PHONY : linalgcpp/fast

#=============================================================================
# Target rules for targets named test_linalg

# Build rule for target.
test_linalg: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_linalg
.PHONY : test_linalg

# fast build rule for target.
test_linalg/fast:
	$(MAKE) -f tests/CMakeFiles/test_linalg.dir/build.make tests/CMakeFiles/test_linalg.dir/build
.PHONY : test_linalg/fast

#=============================================================================
# Target rules for targets named dense_qr

# Build rule for target.
dense_qr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dense_qr
.PHONY : dense_qr

# fast build rule for target.
dense_qr/fast:
	$(MAKE) -f examples/dense/CMakeFiles/dense_qr.dir/build.make examples/dense/CMakeFiles/dense_qr.dir/build
.PHONY : dense_qr/fast

#=============================================================================
# Target rules for targets named dense_lu

# Build rule for target.
dense_lu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dense_lu
.PHONY : dense_lu

# fast build rule for target.
dense_lu/fast:
	$(MAKE) -f examples/dense/CMakeFiles/dense_lu.dir/build.make examples/dense/CMakeFiles/dense_lu.dir/build
.PHONY : dense_lu/fast

#=============================================================================
# Target rules for targets named dense_basics

# Build rule for target.
dense_basics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dense_basics
.PHONY : dense_basics

# fast build rule for target.
dense_basics/fast:
	$(MAKE) -f examples/dense/CMakeFiles/dense_basics.dir/build.make examples/dense/CMakeFiles/dense_basics.dir/build
.PHONY : dense_basics/fast

#=============================================================================
# Target rules for targets named sparse_basics

# Build rule for target.
sparse_basics: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sparse_basics
.PHONY : sparse_basics

# fast build rule for target.
sparse_basics/fast:
	$(MAKE) -f examples/sparse/CMakeFiles/sparse_basics.dir/build.make examples/sparse/CMakeFiles/sparse_basics.dir/build
.PHONY : sparse_basics/fast

#=============================================================================
# Target rules for targets named vector_ops

# Build rule for target.
vector_ops: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vector_ops
.PHONY : vector_ops

# fast build rule for target.
vector_ops/fast:
	$(MAKE) -f examples/vector/CMakeFiles/vector_ops.dir/build.make examples/vector/CMakeFiles/vector_ops.dir/build
.PHONY : vector_ops/fast

src/argparser.o: src/argparser.cpp.o

.PHONY : src/argparser.o

# target to build an object file
src/argparser.cpp.o:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/argparser.cpp.o
.PHONY : src/argparser.cpp.o

src/argparser.i: src/argparser.cpp.i

.PHONY : src/argparser.i

# target to preprocess a source file
src/argparser.cpp.i:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/argparser.cpp.i
.PHONY : src/argparser.cpp.i

src/argparser.s: src/argparser.cpp.s

.PHONY : src/argparser.s

# target to generate assembly for a file
src/argparser.cpp.s:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/argparser.cpp.s
.PHONY : src/argparser.cpp.s

src/blockoperator.o: src/blockoperator.cpp.o

.PHONY : src/blockoperator.o

# target to build an object file
src/blockoperator.cpp.o:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/blockoperator.cpp.o
.PHONY : src/blockoperator.cpp.o

src/blockoperator.i: src/blockoperator.cpp.i

.PHONY : src/blockoperator.i

# target to preprocess a source file
src/blockoperator.cpp.i:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/blockoperator.cpp.i
.PHONY : src/blockoperator.cpp.i

src/blockoperator.s: src/blockoperator.cpp.s

.PHONY : src/blockoperator.s

# target to generate assembly for a file
src/blockoperator.cpp.s:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/blockoperator.cpp.s
.PHONY : src/blockoperator.cpp.s

src/coomatrix.o: src/coomatrix.cpp.o

.PHONY : src/coomatrix.o

# target to build an object file
src/coomatrix.cpp.o:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/coomatrix.cpp.o
.PHONY : src/coomatrix.cpp.o

src/coomatrix.i: src/coomatrix.cpp.i

.PHONY : src/coomatrix.i

# target to preprocess a source file
src/coomatrix.cpp.i:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/coomatrix.cpp.i
.PHONY : src/coomatrix.cpp.i

src/coomatrix.s: src/coomatrix.cpp.s

.PHONY : src/coomatrix.s

# target to generate assembly for a file
src/coomatrix.cpp.s:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/coomatrix.cpp.s
.PHONY : src/coomatrix.cpp.s

src/densematrix.o: src/densematrix.cpp.o

.PHONY : src/densematrix.o

# target to build an object file
src/densematrix.cpp.o:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/densematrix.cpp.o
.PHONY : src/densematrix.cpp.o

src/densematrix.i: src/densematrix.cpp.i

.PHONY : src/densematrix.i

# target to preprocess a source file
src/densematrix.cpp.i:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/densematrix.cpp.i
.PHONY : src/densematrix.cpp.i

src/densematrix.s: src/densematrix.cpp.s

.PHONY : src/densematrix.s

# target to generate assembly for a file
src/densematrix.cpp.s:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/densematrix.cpp.s
.PHONY : src/densematrix.cpp.s

src/eigensolver.o: src/eigensolver.cpp.o

.PHONY : src/eigensolver.o

# target to build an object file
src/eigensolver.cpp.o:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/eigensolver.cpp.o
.PHONY : src/eigensolver.cpp.o

src/eigensolver.i: src/eigensolver.cpp.i

.PHONY : src/eigensolver.i

# target to preprocess a source file
src/eigensolver.cpp.i:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/eigensolver.cpp.i
.PHONY : src/eigensolver.cpp.i

src/eigensolver.s: src/eigensolver.cpp.s

.PHONY : src/eigensolver.s

# target to generate assembly for a file
src/eigensolver.cpp.s:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/eigensolver.cpp.s
.PHONY : src/eigensolver.cpp.s

src/operator.o: src/operator.cpp.o

.PHONY : src/operator.o

# target to build an object file
src/operator.cpp.o:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/operator.cpp.o
.PHONY : src/operator.cpp.o

src/operator.i: src/operator.cpp.i

.PHONY : src/operator.i

# target to preprocess a source file
src/operator.cpp.i:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/operator.cpp.i
.PHONY : src/operator.cpp.i

src/operator.s: src/operator.cpp.s

.PHONY : src/operator.s

# target to generate assembly for a file
src/operator.cpp.s:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/operator.cpp.s
.PHONY : src/operator.cpp.s

src/solvers.o: src/solvers.cpp.o

.PHONY : src/solvers.o

# target to build an object file
src/solvers.cpp.o:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/solvers.cpp.o
.PHONY : src/solvers.cpp.o

src/solvers.i: src/solvers.cpp.i

.PHONY : src/solvers.i

# target to preprocess a source file
src/solvers.cpp.i:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/solvers.cpp.i
.PHONY : src/solvers.cpp.i

src/solvers.s: src/solvers.cpp.s

.PHONY : src/solvers.s

# target to generate assembly for a file
src/solvers.cpp.s:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/solvers.cpp.s
.PHONY : src/solvers.cpp.s

src/sparsematrix.o: src/sparsematrix.cpp.o

.PHONY : src/sparsematrix.o

# target to build an object file
src/sparsematrix.cpp.o:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/sparsematrix.cpp.o
.PHONY : src/sparsematrix.cpp.o

src/sparsematrix.i: src/sparsematrix.cpp.i

.PHONY : src/sparsematrix.i

# target to preprocess a source file
src/sparsematrix.cpp.i:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/sparsematrix.cpp.i
.PHONY : src/sparsematrix.cpp.i

src/sparsematrix.s: src/sparsematrix.cpp.s

.PHONY : src/sparsematrix.s

# target to generate assembly for a file
src/sparsematrix.cpp.s:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/sparsematrix.cpp.s
.PHONY : src/sparsematrix.cpp.s

src/timer.o: src/timer.cpp.o

.PHONY : src/timer.o

# target to build an object file
src/timer.cpp.o:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/timer.cpp.o
.PHONY : src/timer.cpp.o

src/timer.i: src/timer.cpp.i

.PHONY : src/timer.i

# target to preprocess a source file
src/timer.cpp.i:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/timer.cpp.i
.PHONY : src/timer.cpp.i

src/timer.s: src/timer.cpp.s

.PHONY : src/timer.s

# target to generate assembly for a file
src/timer.cpp.s:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/timer.cpp.s
.PHONY : src/timer.cpp.s

src/vector.o: src/vector.cpp.o

.PHONY : src/vector.o

# target to build an object file
src/vector.cpp.o:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/vector.cpp.o
.PHONY : src/vector.cpp.o

src/vector.i: src/vector.cpp.i

.PHONY : src/vector.i

# target to preprocess a source file
src/vector.cpp.i:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/vector.cpp.i
.PHONY : src/vector.cpp.i

src/vector.s: src/vector.cpp.s

.PHONY : src/vector.s

# target to generate assembly for a file
src/vector.cpp.s:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/vector.cpp.s
.PHONY : src/vector.cpp.s

src/vectorview.o: src/vectorview.cpp.o

.PHONY : src/vectorview.o

# target to build an object file
src/vectorview.cpp.o:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/vectorview.cpp.o
.PHONY : src/vectorview.cpp.o

src/vectorview.i: src/vectorview.cpp.i

.PHONY : src/vectorview.i

# target to preprocess a source file
src/vectorview.cpp.i:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/vectorview.cpp.i
.PHONY : src/vectorview.cpp.i

src/vectorview.s: src/vectorview.cpp.s

.PHONY : src/vectorview.s

# target to generate assembly for a file
src/vectorview.cpp.s:
	$(MAKE) -f CMakeFiles/linalgcpp.dir/build.make CMakeFiles/linalgcpp.dir/src/vectorview.cpp.s
.PHONY : src/vectorview.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... test"
	@echo "... list_install_components"
	@echo "... linalgcpp"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... install"
	@echo "... test_linalg"
	@echo "... dense_qr"
	@echo "... dense_lu"
	@echo "... dense_basics"
	@echo "... sparse_basics"
	@echo "... vector_ops"
	@echo "... src/argparser.o"
	@echo "... src/argparser.i"
	@echo "... src/argparser.s"
	@echo "... src/blockoperator.o"
	@echo "... src/blockoperator.i"
	@echo "... src/blockoperator.s"
	@echo "... src/coomatrix.o"
	@echo "... src/coomatrix.i"
	@echo "... src/coomatrix.s"
	@echo "... src/densematrix.o"
	@echo "... src/densematrix.i"
	@echo "... src/densematrix.s"
	@echo "... src/eigensolver.o"
	@echo "... src/eigensolver.i"
	@echo "... src/eigensolver.s"
	@echo "... src/operator.o"
	@echo "... src/operator.i"
	@echo "... src/operator.s"
	@echo "... src/solvers.o"
	@echo "... src/solvers.i"
	@echo "... src/solvers.s"
	@echo "... src/sparsematrix.o"
	@echo "... src/sparsematrix.i"
	@echo "... src/sparsematrix.s"
	@echo "... src/timer.o"
	@echo "... src/timer.i"
	@echo "... src/timer.s"
	@echo "... src/vector.o"
	@echo "... src/vector.i"
	@echo "... src/vector.s"
	@echo "... src/vectorview.o"
	@echo "... src/vectorview.i"
	@echo "... src/vectorview.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

